[package]
name = "procedural_generation"
version = "0.1.0"
authors = ["thomspoon"]
edition = "2024"
build = "build.rs"

[dependencies]
arrayvec = "^0.7"
bitflags = "^2"
glutin = "^0.32"
glutin-winit = "0.5.0"
image = "^0.25"
noise = "0.9"
raw-window-handle = "0.6"
vek = "^0.17"
winit = "0.30"

[build-dependencies]
gl_generator = "^0.14"
